### ISSUE TITLE
Clarify namespace for vk8s services

### ISSUE THREAD

**Issue by JeffGiroux** [f5devcentral/volterra-aks-vk8s-guide#1]
The lab guide can lead to 503 server errors if the wrong k8s namespace is used. For the cloud provider aks services, those reside in 'default' namespace for the tcp lb and also the backend.

However, the vk8s is NOT always in the 'default' namespace. It should be clearly stated in the lab guide that the vk8s services should specify the namespace for which the vk8s is deployed...not necessarily always 'default'. 

## Suggestion
Update wording.

Current...
```
`e)` Enter a unique name for the origin pool, and then select **K8s Service Name of Origin Server on given Sites** as the type of origin server. Note that we will need to indicate the Origin Server **service name**, which follows the format of **servicename.namespace**. For this flow, let's specify **frontend.default**. 
```

Proposed...
```
`e)` Enter a unique name for the origin pool, and then select **K8s Service Name of Origin Server on given Sites** as the type of origin server. Note that we will need to indicate the Origin Server **service name**, which follows the format of **servicename.namespace**. For this flow, use the namespace in which you deployed the vk8s cluster. Let's specify **frontend.<your-vk8s-ns>**
```

## Items Affected
This affects any service on the vk8s cluster. You will need to update the lab guide with proposed wording above for the frontend service as well as the find-a-store-service in the README.

**Comment by yoctoalex** [comment]
Thank you! Has been fixed.
